// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCojFGpxA1Fpy9TRauMbWpGg22eLQcNvEI',
    appId: '1:730282013216:web:906ec2ad0fe9144c3c8245',
    messagingSenderId: '730282013216',
    projectId: 'okrai-36082',
    authDomain: 'okrai-36082.firebaseapp.com',
    storageBucket: 'okrai-36082.firebasestorage.app',
    measurementId: 'G-NPQFSFN5D9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBdHm5CDOnZ-Z2xdFF9we0ak13DTcMmSg8',
    appId: '1:730282013216:android:8f8d96ba1147e99e3c8245',
    messagingSenderId: '730282013216',
    projectId: 'okrai-36082',
    storageBucket: 'okrai-36082.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCojFGpxA1Fpy9TRauMbWpGg22eLQcNvEI',
    appId: '1:730282013216:web:0635ca2ce3e357d23c8245',
    messagingSenderId: '730282013216',
    projectId: 'okrai-36082',
    authDomain: 'okrai-36082.firebaseapp.com',
    storageBucket: 'okrai-36082.firebasestorage.app',
    measurementId: 'G-8DYD97W1HF',
  );
}
